apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: openshift-vertical-pod-autoscaler
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: openshift-vertical-pod-autoscaler
    app.kubernetes.io/component: vertical-pod-autoscaler-operator
    app.kubernetes.io/created-by: vertical-pod-autoscaler-operator
    app.kubernetes.io/part-of: vertical-pod-autoscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: openshift-vertical-pod-autoscaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertical-pod-autoscaler-operator
  namespace: openshift-vertical-pod-autoscaler
spec:
  selector:
    matchLabels:
      k8s-app: vertical-pod-autoscaler-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: vertical-pod-autoscaler-operator
      labels:
        k8s-app: vertical-pod-autoscaler-operator
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: vertical-pod-autoscaler-operator
      containers:
      - name: vertical-pod-autoscaler-operator
        image: quay.io/openshift/origin-vertical-pod-autoscaler-operator:latest
        imagePullPolicy: Always
        command:
        - /manager
        args:
        - --leader-elect
        env:
        - name: RELATED_IMAGE_VPA
          value: quay.io/openshift/origin-vertical-pod-autoscaler:latest
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VERTICAL_POD_AUTOSCALER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
