apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: vertical-pod-autoscaler-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - update
  - list
  - watch
- apiGroups:
  - autoscaling.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - verticalpodoperatorcontrollers
  - verticalpodoperatorcontrollers/status
  verbs:
  - create
  - get
  - update
